"""Run with UnrealEditor-Cmd -run=pythonscript -script=<absolute path>."""
import unreal

assets = unreal.AssetToolsHelpers.get_asset_tools()
path = '/Game/Materials/M_Surface'
material = unreal.load_asset(path)
if not material:
    material = assets.create_asset('M_Surface', '/Game/Materials', unreal.Material, unreal.MaterialFactoryNew())
edit = unreal.MaterialEditingLibrary
def connect(source, output, target, pin):
    if not edit.connect_material_expressions(source, output, target, pin):
        raise RuntimeError(f'Material connection failed: {source.get_name()} -> {target.get_name()} / {pin}')
edit.delete_all_material_expressions(material)
color = edit.create_material_expression(material, unreal.MaterialExpressionVectorParameter, -400, 0)
color.set_editor_property('parameter_name', 'Color')
color.set_editor_property('default_value', unreal.LinearColor(0.2, 0.3, 0.4, 1))
glow = edit.create_material_expression(material, unreal.MaterialExpressionScalarParameter, -400, 180)
glow.set_editor_property('parameter_name', 'Glow')
glow.set_editor_property('default_value', 0.0)
multiply = edit.create_material_expression(material, unreal.MaterialExpressionMultiply, -150, 170)
connect(color, '', multiply, 'A')
connect(glow, '', multiply, 'B')
# Quantized key-light bands retain dynamic cast shadows while reducing plastic highlights.
normal = edit.create_material_expression(material, unreal.MaterialExpressionPixelNormalWS, -1000, -400)
light = edit.create_material_expression(material, unreal.MaterialExpressionConstant3Vector, -1000, -260)
light.set_editor_property('constant', unreal.LinearColor(0.35, -0.55, 0.76, 1))
dot = edit.create_material_expression(material, unreal.MaterialExpressionDotProduct, -800, -400)
connect(normal, '', dot, 'A')
connect(light, '', dot, 'B')
clamp = edit.create_material_expression(material, unreal.MaterialExpressionSaturate, -650, -400)
connect(dot, '', clamp, '')
bands = edit.create_material_expression(material, unreal.MaterialExpressionMultiply, -500, -400)
bands.set_editor_property('const_b', 3.0)
connect(clamp, '', bands, 'A')
step = edit.create_material_expression(material, unreal.MaterialExpressionFloor, -350, -400)
connect(bands, '', step, '')
strength = edit.create_material_expression(material, unreal.MaterialExpressionMultiply, -200, -400)
strength.set_editor_property('const_b', 0.2)
connect(step, '', strength, 'A')
ambient = edit.create_material_expression(material, unreal.MaterialExpressionAdd, -50, -400)
ambient.set_editor_property('const_b', 0.4)
connect(strength, '', ambient, 'A')
paint = edit.create_material_expression(material, unreal.MaterialExpressionMultiply, 100, -200)
connect(color, '', paint, 'A')
connect(ambient, '', paint, 'B')
edit.connect_material_property(paint, '', unreal.MaterialProperty.MP_BASE_COLOR)
edit.connect_material_property(multiply, '', unreal.MaterialProperty.MP_EMISSIVE_COLOR)
roughness = edit.create_material_expression(material, unreal.MaterialExpressionScalarParameter, -150, 350)
roughness.set_editor_property('parameter_name', 'Roughness')
roughness.set_editor_property('default_value', 0.7)
edit.connect_material_property(roughness, '', unreal.MaterialProperty.MP_ROUGHNESS)
metal = edit.create_material_expression(material, unreal.MaterialExpressionScalarParameter, -150, 440)
metal.set_editor_property('parameter_name', 'Metallic')
metal.set_editor_property('default_value', 0.08)
edit.connect_material_property(metal, '', unreal.MaterialProperty.MP_METALLIC)
edit.recompile_material(material)
unreal.EditorAssetLibrary.save_asset(path)
from pathlib import Path
for wav in (Path(__file__).parent / 'GeneratedAudio').glob('*.wav'):
    task = unreal.AssetImportTask()
    task.set_editor_property('filename', str(wav))
    task.set_editor_property('destination_path', '/Game/Audio')
    task.set_editor_property('automated', True)
    task.set_editor_property('replace_existing', True)
    task.set_editor_property('save', True)
    assets.import_asset_tasks([task])
level = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
if not unreal.EditorAssetLibrary.does_asset_exist('/Game/Maps/LastSignal'):
    level.new_level('/Game/Maps/LastSignal')
    level.save_current_level()
unreal.log('EVA_CONTENT_OK')
